# Generated by Django 3.1 on 2021-02-13 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20210213_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='class_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quickstart.classsession'),
            preserve_default=False,
        ),
    ]
