# Generated by Django 3.1 on 2021-02-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_question_class_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answerIndex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answerText',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
