# Generated by Django 3.1 on 2021-02-13 18:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20210213_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answerText',
        ),
        migrations.AlterField(
            model_name='question',
            name='answerIndex',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
    ]
