# Generated by Django 3.1 on 2021-02-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_auto_20210213_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='bar_graph',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='classsession',
            name='scatter_plot',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
