# Generated by Django 3.1 on 2021-02-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_auto_20210214_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='bar_graph',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='scatter_plot',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
