# Generated by Django 3.1 on 2021-02-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_auto_20210214_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classsession',
            old_name='bar_graph',
            new_name='bar_plot',
        ),
        migrations.AddField(
            model_name='classsession',
            name='line_plot',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
